name: Build and Zip Plugin

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Zip
        run: sudo apt-get install zip

      - name: Increment Minor Version
        run: |
            FILE=wordpress-utils-plugin.php 
            VERSION=$(grep -oP 'Version: \K[\d.]+' $FILE)
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            PATCH=$(echo $VERSION | cut -d. -f3)
            NEW_MINOR=$((MINOR+1))
            NEW_VERSION="$MAJOR.$NEW_MINOR.$PATCH"
            sed -i "s/Version: $VERSION/Version: $NEW_VERSION/" $FILE
            echo "Updated version to $NEW_VERSION"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'update plugin to new version [skip ci]'

      - name: Zip the Plugin
        run: zip -r ../wordpress-utils-plugin.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wordpress-utils-plugin
          path: wordpress-utils-plugin.zip
